CREATE TABLE customers (
  id BINARY(16) NOT NULL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
  id BINARY(16) NOT NULL PRIMARY KEY,
  customer_id BINARY(16) NOT NULL,
  account_number VARCHAR(30) NOT NULL UNIQUE,
  account_type VARCHAR(20) NOT NULL,
  currency VARCHAR(10) NOT NULL,
  balance DECIMAL(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) DEFAULT 'ACTIVE',
  version BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE transactions (
  id BINARY(16) NOT NULL PRIMARY KEY,
  account_id BINARY(16) NOT NULL,
  type VARCHAR(30) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  balance_after DECIMAL(18,2),
  reference_id BINARY(16),
  status VARCHAR(20) DEFAULT 'SUCCESS',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  metadata JSON,
  CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE TABLE idempotency_keys (
  id BINARY(16) NOT NULL PRIMARY KEY,
  key_value VARCHAR(255) NOT NULL UNIQUE,
  response JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
